INSERT INTO complaint_codes (descriptor, severity_level)
VALUES
  ('Loud Music/Party', 3),
  ('Banging/Pounding', 2),
  ('Car/Truck Horn', 2),
  ('Car/Truck Music', 2),
  ('Engine Idling', 1),
  ('Loud Talking', 1),
  ('Loud Television', 1),
  ('NYPD', 1),
  ('News Gathering', 1),
  ('Noise, Barking Dog (NR5)', 2),
  ('Noise, Ice Cream Truck (NR4)', 1),
  ('Noise, Other Animals (NR6)', 1),
  ('Noise:  lawn care equipment (NCL)', 1),
  ('Noise: Alarms (NR3)', 3),
  ('Noise: Boat(Engine,Music,Etc) (NR10)', 2),
  ('Noise: Construction Before/After Hours (NM1)', 3),
  ('Noise: Construction Equipment (NC1)', 2),
  ('Noise: Jack Hammering (NC2)', 3),
  ('Noise: Manufacturing Noise (NK1)', 2),
  ('Noise: Private Carting Noise (NQ1)', 2),
  ('Noise: air condition/ventilation equipment (NV1)', 1),
  ('Other', 1);
